# service/url_service.py
from src.repository.url_repository import UrlRepository
from src.entity.url_mapping import UrlMapping

class UrlService:

    def __init__(self, repository: UrlRepository):
        self.repository = repository

    def create_short_url(self, long_url: str):

        short_code = "AbC123"   # generated by your Base62 encoder

        url_mapping = UrlMapping(
            short_code=short_code,
            long_url=long_url,
            click_count=0
        )

        saved = self.repository.save(url_mapping)

        return saved